services:
  php:
    build: /
    container_name: xin-admin
    # 如果要在生产环境中运行，请取消注释以下行
    # restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # 在生产环境中注释以下行，它允许在 dev 中使用清晰可读日志
    tty: true
volumes:
  caddy_data:
  caddy_config: